{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "script-assembler-plugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "script-assembler-plugin-1.0.1.jar",
          "url": "script-assembler-plugin-1.0.1.jar",
          "size": 7060,
          "sha512": "ee5b6301b0b4e9b6dee1398b3f283b2770b656428073fdefd0dc48c0d7f3c24ff8188ff4829a42fb28ff67c3203e7bf2ed227195b4e5c54ff9b711949ca40168",
          "sha256": "c22c5a37ce07aa09e0b71e8575a85d927534fd3d89e295cbf5817b520ee169d4",
          "sha1": "def074527b0de2daf95c0fc4ca995849bb946573",
          "md5": "3f035f1132780cf151adba2070cd57e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.8-1"
          }
        },
        {
          "group": "net.runelite",
          "module": "cache",
          "version": {
            "requires": "1.8.25"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "script-assembler-plugin-1.0.1.jar",
          "url": "script-assembler-plugin-1.0.1.jar",
          "size": 7060,
          "sha512": "ee5b6301b0b4e9b6dee1398b3f283b2770b656428073fdefd0dc48c0d7f3c24ff8188ff4829a42fb28ff67c3203e7bf2ed227195b4e5c54ff9b711949ca40168",
          "sha256": "c22c5a37ce07aa09e0b71e8575a85d927534fd3d89e295cbf5817b520ee169d4",
          "sha1": "def074527b0de2daf95c0fc4ca995849bb946573",
          "md5": "3f035f1132780cf151adba2070cd57e3"
        }
      ]
    }
  ]
}
