{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.11.jar",
          "url": "injector-plugin-2.0.11.jar",
          "size": 136124,
          "sha512": "a3e1f5a2c172c72e9f7455dab3f39e92dbcb7ce4d0991fbcf77f4ea0e19512597691d0f4ea2ae9a9bb8922c941edf9c4d71c0756a4e7f5fa58ac9592a6788894",
          "sha256": "cd7c5fdc31c6f6c14864b7dcc1ca6f6edb10453038260d739ba307f6c4f3bf62",
          "sha1": "bdb5c6dff9c84751dcdd075531c1ebd6eb810263",
          "md5": "68e9292aea204f3c4c1d7bcd9ff06a3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "net.unethicalite",
          "module": "deobfuscator",
          "version": {
            "requires": "1.0.14-EXPERIMENTAL"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.11.jar",
          "url": "injector-plugin-2.0.11.jar",
          "size": 136124,
          "sha512": "a3e1f5a2c172c72e9f7455dab3f39e92dbcb7ce4d0991fbcf77f4ea0e19512597691d0f4ea2ae9a9bb8922c941edf9c4d71c0756a4e7f5fa58ac9592a6788894",
          "sha256": "cd7c5fdc31c6f6c14864b7dcc1ca6f6edb10453038260d739ba307f6c4f3bf62",
          "sha1": "bdb5c6dff9c84751dcdd075531c1ebd6eb810263",
          "md5": "68e9292aea204f3c4c1d7bcd9ff06a3e"
        }
      ]
    }
  ]
}
