{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.14-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.14-EXPERIMENTAL.jar",
          "url": "runelite-api-1.0.14-EXPERIMENTAL.jar",
          "size": 1448551,
          "sha512": "f583b05d21a6c41486babbd3d88976d3f8ada57517e40d5306d9caf7352a3bd3f8c1487cdcdb85c9b59e967bb399c08eeba6acef10c6cf8993f648a010b30972",
          "sha256": "2427bceab469f8e605f40670fda931ae129713ff141a7071add4ab73c2a866b5",
          "sha1": "4eda6c5426cc09d96512ad9f3243533759deba0a",
          "md5": "bac8b5bf72eb63a2393744cbf8f1b535"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.14-EXPERIMENTAL.jar",
          "url": "runelite-api-1.0.14-EXPERIMENTAL.jar",
          "size": 1448551,
          "sha512": "f583b05d21a6c41486babbd3d88976d3f8ada57517e40d5306d9caf7352a3bd3f8c1487cdcdb85c9b59e967bb399c08eeba6acef10c6cf8993f648a010b30972",
          "sha256": "2427bceab469f8e605f40670fda931ae129713ff141a7071add4ab73c2a866b5",
          "sha1": "4eda6c5426cc09d96512ad9f3243533759deba0a",
          "md5": "bac8b5bf72eb63a2393744cbf8f1b535"
        }
      ]
    }
  ]
}
